// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2h60Tv-jGzKhuSaJ_KxhoPAzLsQf8B8A',
    appId: '1:971825042936:web:2ed941d2f295148094320d',
    messagingSenderId: '971825042936',
    projectId: 'dummy-proj-221a5',
    authDomain: 'dummy-proj-221a5.firebaseapp.com',
    storageBucket: 'dummy-proj-221a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDirF22nDV4775UxkBiNrXXq_gNrgVwX6Q',
    appId: '1:971825042936:android:290b653e0846938094320d',
    messagingSenderId: '971825042936',
    projectId: 'dummy-proj-221a5',
    storageBucket: 'dummy-proj-221a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8CvMFEOBTelh6l4QnjaaVSUulhm4xW4k',
    appId: '1:971825042936:ios:2f68dc458f45a8e294320d',
    messagingSenderId: '971825042936',
    projectId: 'dummy-proj-221a5',
    storageBucket: 'dummy-proj-221a5.appspot.com',
    androidClientId: '971825042936-4r9nckjhpl6s6iibam0mjlp4o0lg1d5b.apps.googleusercontent.com',
    iosClientId: '971825042936-lvccn3nr4fhbl981fkr7ho0v86qeci8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.dummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8CvMFEOBTelh6l4QnjaaVSUulhm4xW4k',
    appId: '1:971825042936:ios:2f68dc458f45a8e294320d',
    messagingSenderId: '971825042936',
    projectId: 'dummy-proj-221a5',
    storageBucket: 'dummy-proj-221a5.appspot.com',
    androidClientId: '971825042936-4r9nckjhpl6s6iibam0mjlp4o0lg1d5b.apps.googleusercontent.com',
    iosClientId: '971825042936-lvccn3nr4fhbl981fkr7ho0v86qeci8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.dummy',
  );
}
